"""float to numeric

Revision ID: 1197c41e38c9
Revises: 367499279807
Create Date: 2026-04-28 10:12:47.488776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1197c41e38c9'
down_revision = '367499279807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anticipos', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('cant_kg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)

    with op.batch_alter_table('conceptos_retencion_ganancias', schema=None) as batch_op:
        batch_op.alter_column('mni_inscripto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('alicuota_inscripto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)
        batch_op.alter_column('alicuota_no_inscripto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)
        batch_op.alter_column('min_retencion_inscripto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('min_retencion_no_inscripto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('cuenta_corriente', schema=None) as batch_op:
        batch_op.alter_column('debe',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('haber',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('cuentas_asignacion', schema=None) as batch_op:
        batch_op.alter_column('cant_kg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)
        batch_op.alter_column('monto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('escalas_ganancias', schema=None) as batch_op:
        batch_op.alter_column('desde',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('hasta',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monto_fijo',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('alicuota_marginal',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)
        batch_op.alter_column('excedente_sobre',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('facturas_compra', schema=None) as batch_op:
        batch_op.alter_column('neto_gravado',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('neto_no_gravado',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('iva_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('imp_internos_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('percep_iva',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('percep_iibb',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('otros_impuestos',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('facturas_compra_items', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)
        batch_op.alter_column('costo_unitario',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('subtotal_neto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('iva_alicuota',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)
        batch_op.alter_column('iva_monto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('imp_internos',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('movimientos_tela', schema=None) as batch_op:
        batch_op.alter_column('cant_kg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)
        batch_op.alter_column('precio_sin_iva',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('precio_con_iva',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('percp_iva',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('percp_iibb',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('subtotal_iva',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('dif_kg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)

    with op.batch_alter_table('notas_credito', schema=None) as batch_op:
        batch_op.alter_column('monto_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('iva',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monto_con_iva',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('notas_credito_items', schema=None) as batch_op:
        batch_op.alter_column('kg_aceptados',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)
        batch_op.alter_column('monto_aceptado',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('pago_factura', schema=None) as batch_op:
        batch_op.alter_column('monto_aplicado',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('monto_bruto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_retenciones',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monto_neto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.alter_column('kg_totales',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)

    with op.batch_alter_table('pedido_detalles', schema=None) as batch_op:
        batch_op.alter_column('cant_kg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)
        batch_op.alter_column('precio_unitario',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('retenciones_ganancias', schema=None) as batch_op:
        batch_op.alter_column('monto_sujeto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('base_imponible',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('base_acumulada',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('mni_aplicado',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('base_sujeta',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('impuesto_teorico',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('retenido_previo',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('retencion',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monto_neto',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retenciones_ganancias', schema=None) as batch_op:
        batch_op.alter_column('monto_neto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('retencion',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('retenido_previo',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('impuesto_teorico',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('base_sujeta',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('mni_aplicado',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('base_acumulada',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('base_imponible',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monto_sujeto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('pedido_detalles', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('precio_unitario',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('cant_kg',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.alter_column('kg_totales',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('monto_neto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_retenciones',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monto_bruto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('pago_factura', schema=None) as batch_op:
        batch_op.alter_column('monto_aplicado',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('notas_credito_items', schema=None) as batch_op:
        batch_op.alter_column('monto_aceptado',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('kg_aceptados',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('notas_credito', schema=None) as batch_op:
        batch_op.alter_column('monto_con_iva',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('iva',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monto_total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('movimientos_tela', schema=None) as batch_op:
        batch_op.alter_column('dif_kg',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('subtotal_iva',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('percp_iibb',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('percp_iva',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('precio_con_iva',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('precio_sin_iva',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('cant_kg',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('facturas_compra_items', schema=None) as batch_op:
        batch_op.alter_column('imp_internos',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('iva_monto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('iva_alicuota',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('subtotal_neto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('costo_unitario',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('facturas_compra', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('otros_impuestos',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('percep_iibb',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('percep_iva',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('imp_internos_total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('iva_total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('neto_no_gravado',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('neto_gravado',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('escalas_ganancias', schema=None) as batch_op:
        batch_op.alter_column('excedente_sobre',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('alicuota_marginal',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monto_fijo',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('hasta',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('desde',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('cuentas_asignacion', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('cant_kg',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('cuenta_corriente', schema=None) as batch_op:
        batch_op.alter_column('haber',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('debe',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('conceptos_retencion_ganancias', schema=None) as batch_op:
        batch_op.alter_column('min_retencion_no_inscripto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('min_retencion_inscripto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('alicuota_no_inscripto',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('alicuota_inscripto',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('mni_inscripto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('anticipos', schema=None) as batch_op:
        batch_op.alter_column('cant_kg',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monto',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
