"""initial schema

Revision ID: 367499279807
Revises: 
Create Date: 2026-04-27 14:43:46.167767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367499279807'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conceptos_retencion_ganancias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('mni_inscripto', sa.Float(), nullable=True),
    sa.Column('alicuota_inscripto', sa.Float(), nullable=True),
    sa.Column('tipo_inscripto', sa.String(length=20), nullable=True),
    sa.Column('alicuota_no_inscripto', sa.Float(), nullable=True),
    sa.Column('tipo_no_inscripto', sa.String(length=20), nullable=True),
    sa.Column('min_retencion_inscripto', sa.Float(), nullable=True),
    sa.Column('min_retencion_no_inscripto', sa.Float(), nullable=True),
    sa.Column('escala_aplicable', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('escalas_ganancias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('desde', sa.Float(), nullable=True),
    sa.Column('hasta', sa.Float(), nullable=True),
    sa.Column('monto_fijo', sa.Float(), nullable=True),
    sa.Column('alicuota_marginal', sa.Float(), nullable=True),
    sa.Column('excedente_sobre', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=20), nullable=True),
    sa.Column('entidad', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('condicion_pago_dias', sa.Integer(), nullable=True),
    sa.Column('usa_cuentas_asignacion', sa.Boolean(), nullable=True),
    sa.Column('condicion_ganancias', sa.String(length=20), nullable=True),
    sa.Column('concepto_retencion_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concepto_retencion_id'], ['conceptos_retencion_ganancias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anticipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('cant_kg', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuenta_corriente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('numero_comprobante', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cuenta', sa.String(length=20), nullable=True),
    sa.Column('debe', sa.Float(), nullable=True),
    sa.Column('haber', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maestro_telas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('tipo_tela', sa.String(length=50), nullable=False),
    sa.Column('cod_art', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('cod_color', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('cuenta_piezas', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor_id', 'tipo_tela', 'cod_art', 'color', 'cod_color', name='uq_maestro_tela')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('agente_codigo', sa.String(length=20), nullable=True),
    sa.Column('agente_cuit', sa.String(length=20), nullable=True),
    sa.Column('agente_nombre', sa.String(length=100), nullable=True),
    sa.Column('medio_pago', sa.String(length=50), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('monto_bruto', sa.Float(), nullable=True),
    sa.Column('total_retenciones', sa.Float(), nullable=True),
    sa.Column('monto_neto', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('tipo_tela', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('cod_art', sa.String(length=30), nullable=True),
    sa.Column('cod_color', sa.String(length=30), nullable=True),
    sa.Column('piezas_totales', sa.Integer(), nullable=True),
    sa.Column('kg_totales', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor_id', 'numero', name='uq_partida_proveedor_numero')
    )
    op.create_table('cuentas_asignacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anticipo_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('tipo_tela', sa.String(length=50), nullable=True),
    sa.Column('cant_kg', sa.Float(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anticipo_id'], ['anticipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('tipo_comprobante', sa.String(length=10), nullable=True),
    sa.Column('punto_venta', sa.String(length=10), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('cuenta', sa.String(length=20), nullable=True),
    sa.Column('neto_gravado', sa.Float(), nullable=True),
    sa.Column('neto_no_gravado', sa.Float(), nullable=True),
    sa.Column('iva_total', sa.Float(), nullable=True),
    sa.Column('imp_internos_total', sa.Float(), nullable=True),
    sa.Column('percep_iva', sa.Float(), nullable=True),
    sa.Column('percep_iibb', sa.Float(), nullable=True),
    sa.Column('otros_impuestos', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('cc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cc_id'], ['cuenta_corriente.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor_id', 'tipo_documento', 'tipo_comprobante', 'punto_venta', 'numero', name='uq_factura_compra_doc_proveedor_numero')
    )
    op.create_table('notas_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('cuenta', sa.String(length=20), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('monto_con_iva', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('cc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cc_id'], ['cuenta_corriente.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('cc_factura_id', sa.Integer(), nullable=False),
    sa.Column('monto_aplicado', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cc_factura_id'], ['cuenta_corriente.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('anticipo_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anticipo_id'], ['anticipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retenciones_ganancias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mes_anio', sa.String(length=7), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('condicion', sa.String(length=20), nullable=True),
    sa.Column('agente_cuit', sa.String(length=20), nullable=True),
    sa.Column('agente_nombre', sa.String(length=100), nullable=True),
    sa.Column('numero_comprobante', sa.String(length=50), nullable=True),
    sa.Column('monto_sujeto', sa.Float(), nullable=True),
    sa.Column('base_imponible', sa.Float(), nullable=True),
    sa.Column('base_acumulada', sa.Float(), nullable=True),
    sa.Column('mni_aplicado', sa.Float(), nullable=True),
    sa.Column('base_sujeta', sa.Float(), nullable=True),
    sa.Column('impuesto_teorico', sa.Float(), nullable=True),
    sa.Column('retenido_previo', sa.Float(), nullable=True),
    sa.Column('retencion', sa.Float(), nullable=True),
    sa.Column('monto_neto', sa.Float(), nullable=True),
    sa.Column('alicuota_aplicada', sa.String(length=30), nullable=True),
    sa.Column('cc_pago_id', sa.Integer(), nullable=True),
    sa.Column('cc_retencion_id', sa.Integer(), nullable=True),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cc_pago_id'], ['cuenta_corriente.id'], ),
    sa.ForeignKeyConstraint(['cc_retencion_id'], ['cuenta_corriente.id'], ),
    sa.ForeignKeyConstraint(['concepto_id'], ['conceptos_retencion_ganancias.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas_compra_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('subtotal_neto', sa.Float(), nullable=True),
    sa.Column('iva_alicuota', sa.Float(), nullable=True),
    sa.Column('iva_monto', sa.Float(), nullable=True),
    sa.Column('imp_internos', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=60), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_tela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cuenta', sa.String(length=20), nullable=True),
    sa.Column('remito_factura', sa.String(length=50), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_pedido', sa.String(length=50), nullable=True),
    sa.Column('tipo_tela', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('cod_art', sa.String(length=20), nullable=True),
    sa.Column('cod_color', sa.String(length=20), nullable=True),
    sa.Column('cant_kg', sa.Float(), nullable=True),
    sa.Column('piezas', sa.Integer(), nullable=True),
    sa.Column('partida', sa.String(length=50), nullable=True),
    sa.Column('precio_sin_iva', sa.Float(), nullable=True),
    sa.Column('precio_con_iva', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('percp_iva', sa.Float(), nullable=True),
    sa.Column('percp_iibb', sa.Float(), nullable=True),
    sa.Column('subtotal_iva', sa.Float(), nullable=True),
    sa.Column('dif_kg', sa.Float(), nullable=True),
    sa.Column('movimiento', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('temporada', sa.String(length=50), nullable=True),
    sa.Column('op', sa.String(length=50), nullable=True),
    sa.Column('anticipo_id', sa.Integer(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_asignacion_id', sa.Integer(), nullable=True),
    sa.Column('partida_id', sa.Integer(), nullable=True),
    sa.Column('maestro_tela_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anticipo_id'], ['anticipos.id'], ),
    sa.ForeignKeyConstraint(['cuenta_asignacion_id'], ['cuentas_asignacion.id'], ),
    sa.ForeignKeyConstraint(['maestro_tela_id'], ['maestro_telas.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('tipo_tela', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('cod_art', sa.String(length=20), nullable=True),
    sa.Column('cod_color', sa.String(length=20), nullable=True),
    sa.Column('cant_kg', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_credito_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nc_id', sa.Integer(), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('kg_aceptados', sa.Float(), nullable=True),
    sa.Column('monto_aceptado', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_tela.id'], ),
    sa.ForeignKeyConstraint(['nc_id'], ['notas_credito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas_credito_items')
    op.drop_table('pedido_detalles')
    op.drop_table('movimientos_tela')
    op.drop_table('facturas_compra_items')
    op.drop_table('retenciones_ganancias')
    op.drop_table('pedidos')
    op.drop_table('pago_factura')
    op.drop_table('notas_credito')
    op.drop_table('facturas_compra')
    op.drop_table('cuentas_asignacion')
    op.drop_table('partidas')
    op.drop_table('pagos')
    op.drop_table('maestro_telas')
    op.drop_table('cuenta_corriente')
    op.drop_table('anticipos')
    op.drop_table('proveedores')
    op.drop_table('auditoria')
    op.drop_table('usuarios')
    op.drop_table('escalas_ganancias')
    op.drop_table('conceptos_retencion_ganancias')
    # ### end Alembic commands ###
