"""add indexes

Revision ID: c3428470c32b
Revises: 1197c41e38c9
Create Date: 2026-04-28 15:18:24.843541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3428470c32b'
down_revision = '1197c41e38c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anticipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anticipos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_anticipos_numero_factura'), ['numero_factura'], unique=False)
        batch_op.create_index(batch_op.f('ix_anticipos_proveedor_id'), ['proveedor_id'], unique=False)

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_entidad'), ['entidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_fecha'), ['fecha'], unique=False)

    with op.batch_alter_table('cuenta_corriente', schema=None) as batch_op:
        batch_op.create_index('ix_cc_proveedor_comprobante', ['proveedor_id', 'numero_comprobante'], unique=False)
        batch_op.create_index('ix_cc_proveedor_fecha', ['proveedor_id', 'fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_cuenta_corriente_tipo'), ['tipo'], unique=False)

    with op.batch_alter_table('cuentas_asignacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cuentas_asignacion_anticipo_id'), ['anticipo_id'], unique=False)

    with op.batch_alter_table('facturas_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_compra_cc_id'), ['cc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_compra_proveedor_id'), ['proveedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_compra_tipo_documento'), ['tipo_documento'], unique=False)

    with op.batch_alter_table('facturas_compra_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_compra_items_factura_id'), ['factura_id'], unique=False)

    with op.batch_alter_table('movimientos_tela', schema=None) as batch_op:
        batch_op.create_index('ix_mov_proveedor_fecha', ['proveedor_id', 'fecha'], unique=False)
        batch_op.create_index('ix_mov_proveedor_remito', ['proveedor_id', 'remito_factura'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_tela_anticipo_id'), ['anticipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_tela_cuenta_asignacion_id'), ['cuenta_asignacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_tela_maestro_tela_id'), ['maestro_tela_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_tela_movimiento'), ['movimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_tela_partida_id'), ['partida_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_tela_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_tela_tipo_tela'), ['tipo_tela'], unique=False)

    with op.batch_alter_table('notas_credito', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_credito_cc_id'), ['cc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_credito_proveedor_id'), ['proveedor_id'], unique=False)

    with op.batch_alter_table('notas_credito_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_credito_items_movimiento_id'), ['movimiento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_credito_items_nc_id'), ['nc_id'], unique=False)

    with op.batch_alter_table('pago_factura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pago_factura_cc_factura_id'), ['cc_factura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pago_factura_pago_id'), ['pago_id'], unique=False)

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_agente_codigo'), ['agente_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_proveedor_id'), ['proveedor_id'], unique=False)

    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partidas_proveedor_id'), ['proveedor_id'], unique=False)

    with op.batch_alter_table('pedido_detalles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_detalles_pedido_id'), ['pedido_id'], unique=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_anticipo_id'), ['anticipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_estado'), ['estado'], unique=False)

    with op.batch_alter_table('retenciones_ganancias', schema=None) as batch_op:
        batch_op.create_index('ix_ret_acum_mensual', ['proveedor_id', 'concepto_id', 'mes_anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_retenciones_ganancias_agente_cuit'), ['agente_cuit'], unique=False)
        batch_op.create_index(batch_op.f('ix_retenciones_ganancias_cc_pago_id'), ['cc_pago_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retenciones_ganancias_cc_retencion_id'), ['cc_retencion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retenciones_ganancias_concepto_id'), ['concepto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retenciones_ganancias_mes_anio'), ['mes_anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_retenciones_ganancias_pago_id'), ['pago_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retenciones_ganancias_proveedor_id'), ['proveedor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retenciones_ganancias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retenciones_ganancias_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_retenciones_ganancias_pago_id'))
        batch_op.drop_index(batch_op.f('ix_retenciones_ganancias_mes_anio'))
        batch_op.drop_index(batch_op.f('ix_retenciones_ganancias_concepto_id'))
        batch_op.drop_index(batch_op.f('ix_retenciones_ganancias_cc_retencion_id'))
        batch_op.drop_index(batch_op.f('ix_retenciones_ganancias_cc_pago_id'))
        batch_op.drop_index(batch_op.f('ix_retenciones_ganancias_agente_cuit'))
        batch_op.drop_index('ix_ret_acum_mensual')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_estado'))
        batch_op.drop_index(batch_op.f('ix_pedidos_anticipo_id'))

    with op.batch_alter_table('pedido_detalles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_detalles_pedido_id'))

    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partidas_proveedor_id'))

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_numero'))
        batch_op.drop_index(batch_op.f('ix_pagos_agente_codigo'))

    with op.batch_alter_table('pago_factura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pago_factura_pago_id'))
        batch_op.drop_index(batch_op.f('ix_pago_factura_cc_factura_id'))

    with op.batch_alter_table('notas_credito_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_credito_items_nc_id'))
        batch_op.drop_index(batch_op.f('ix_notas_credito_items_movimiento_id'))

    with op.batch_alter_table('notas_credito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_credito_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_notas_credito_cc_id'))

    with op.batch_alter_table('movimientos_tela', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_tela_tipo_tela'))
        batch_op.drop_index(batch_op.f('ix_movimientos_tela_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_tela_partida_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_tela_movimiento'))
        batch_op.drop_index(batch_op.f('ix_movimientos_tela_maestro_tela_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_tela_cuenta_asignacion_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_tela_anticipo_id'))
        batch_op.drop_index('ix_mov_proveedor_remito')
        batch_op.drop_index('ix_mov_proveedor_fecha')

    with op.batch_alter_table('facturas_compra_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_compra_items_factura_id'))

    with op.batch_alter_table('facturas_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_compra_tipo_documento'))
        batch_op.drop_index(batch_op.f('ix_facturas_compra_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_facturas_compra_cc_id'))

    with op.batch_alter_table('cuentas_asignacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuentas_asignacion_anticipo_id'))

    with op.batch_alter_table('cuenta_corriente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuenta_corriente_tipo'))
        batch_op.drop_index('ix_cc_proveedor_fecha')
        batch_op.drop_index('ix_cc_proveedor_comprobante')

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_fecha'))
        batch_op.drop_index(batch_op.f('ix_auditoria_entidad'))
        batch_op.drop_index(batch_op.f('ix_auditoria_accion'))

    with op.batch_alter_table('anticipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anticipos_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_anticipos_numero_factura'))
        batch_op.drop_index(batch_op.f('ix_anticipos_estado'))

    # ### end Alembic commands ###
